services:
  db:
    image: postgres
    restart: never
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
