services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
